name: Cypress Tests
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Run Cypress tests 🧪
        uses: cypress-io/github-action@v4
        with:
          record: true
          parallel: true
          start: npm start
          wait-on: "http://localhost:3000"
        env:
          # pass the record key as environment variable
          # during this CI step
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
